config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root :to => redirect('/entrar')
    
  devise_for :professionals, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'profissional/senha', confirmation: 'profissional/confirmar', unlock: 'profissional/desbloquear', sign_up: 'profissional/cadastrar' }, controllers: { sessions: 'sessions', registrations: 'devise/professional_registrations', confirmations: 'devise/professional_confirmations' }
  devise_for :customers, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'cliente/senha', confirmation: 'cliente/confirmar', unlock: 'cliente/desbloquear' }, controllers: { sessions: 'sessions' }, skip: ['registrations']

  as :customer do

    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'cliente' do
      root 'customers#minhas_safiras_por_profissionais', as: :customer_root
      get 'fotos/:token', to: 'photos#index', as: :my_photos
      post 'assign_rewards_to_customer', to: 'rewards#assign_rewards_to_customer', as: :assign_rewards_to_customer
    end
  end

  as :professional do
    
    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'profissional' do
      root 'photos#new', as: :professional_root

      resources :sign_up_steps, only: [:index, :show, :update]
      resources :photos, only: [:new, :create, :destroy]
      post 'get_rewards_by_customers_telephone/', to: 'rewards#get_rewards_by_customers_telephone', as: :get_rewards_by_customers_telephone
      post 'notificacao', to: 'notifications#new', as: :new_notification
    end
  end

  get 'retorno-pagamento', to: 'notifications#retorno_pagamento', as: :retorno_pagamento

  mount Sidekiq::Web, at: '/sidekiq'

  get ":slug", to: 'photos#my_site', as: :professionals_site

  # Esta rota TEM que ser a última da listagem, pois
  # seu objetivo é redirecionar o usuário para uma
  # página 404 no caso onde a rota não existe.
  match '*path', via: :all, to: 'static_pages#error_404'
end

app/models/reward.rb
# == Schema Information
#
# Table name: rewards
#
#  id              :integer          not null, primary key
#  professional_id :integer
#  customer_id     :integer
#  total_safiras   :integer          default(0)
#  created_at      :datetime
#  updated_at      :datetime
#

class Reward < ActiveRecord::Base
  belongs_to :customer
  belongs_to :professional
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # before_action :set_reward, only: [:show, :edit, :update, :destroy]

  # # GET /schedules
  # # GET /schedules.json
  # def index
  # end

  # # GET /schedules/1
  # # GET /schedules/1.json
  # def show
  # end

  # # GET /schedules/new
  # def new
  # end

  # # GET /schedules/1/edit
  # def edit
  # end

  # # POST /schedules
  # # POST /schedules.json
  # def create
  # end

  # # PATCH/PUT /schedules/1
  # # PATCH/PUT /schedules/1.json
  # def update
  # end

  # # DELETE /schedules/1
  # # DELETE /schedules/1.json
  # def destroy
  # end

  def get_rewards_by_customers_telephone
    ctm = Customer.find_or_initialize_by(telefone: params[:telefone])
    prof = current_professional
    tSafiras = Reward.find_or_initialize_by(professional: prof, customer: ctm).total_safiras
    
    render json: { tSafiras: tSafiras, cId: ctm.id }
  end

  def assign_rewards_to_customer
    @photo = Photo.find_by_id(params[:photo_id])
    Photo.increment_counter(:share_count, @photo)

    if cliente_divulgando_por_recompensa?
      @ci = @photo.customer_invitation
      @rewards = @ci.award_rewards(@photo.id)
    end

    respond_to do |format|
      format.js { render :assign_rewards_to_customer }
    end
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_reward
  #     @reward = Reward.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def reward_params
  #     data = params.require(:reward).permit()
  #   end

  def cliente_divulgando_por_recompensa?
    params[:recompensar].present?
  end

end

app/views/rewards/assign_rewards_to_customer.js.erb
// Se o cliente não tem sessão aberta, significa que ele também não tem cadastro no safiras.
// Isso porque um cliente que tenha cadastro não pode mais divulgar sem antes fazer login.
// Assim sendo, se cliente não tem sessão aberta, abro modal incentivando-o a cadastrar.
<% if params[:recompensar].present? %>
  $(".modal").modal("hide")

  <% if current_customer.blank? %>
    bootbox.dialog({
      title: "ÓTIMAS NOTÍCAS! <span class='text-strong'>Você foi recompensado!</span>",
      message: "<p>Você recebeu <span class='text-strong'><%= pluralize(@ci.recompensa, 'safira') %></span> como recompensa pela divulgação realizada.</p> <p><span class='text-strong'>Salve suas recompensas</span> cadastrando-se abaixo e <span class='text-strong'>obtenha descontos</span> trocando-as com <%= @photo.professional.nome %> nos próximos atendimentos.</p>",
      buttons: {
        success: {
          label: "<span style='color: white'><i class='fa fa-facebook'></i><b style='padding-left: 20px'>Entre com o Facebook</b></span>",
          className: 'btn-fb btn-block normal-white-space',
          callback: function() {
            return window.location.href = "/auth/facebook?scope=email&action=signup_customer&photo_id=<%= @photo.id %>&telefone=<%= @ci.customer_telefone %>";
          }
        }
      }
    });
  <% else %>
    bootbox.dialog({
      title: "ÓTIMAS NOTÍCAS! <span class='text-strong'>Você foi recompensado!</span>",
      message: "<p>Você recebeu <span class='text-strong'><%= pluralize(@ci.recompensa, 'safira') %></span> como recompensa pela divulgação realizada.</p>",
      buttons: {
        success: {
          label: "<span style='color: white'><b>Ver Minhas Recompensas</b></span>",
          className: 'btn-fb btn-block',
          callback: function() {
            return window.location.href = "<%= customer_root_path %>";
          }
        }
      }
    });
  <% end %>
<% end %>

// Se cliente presente, minha resposta deverá ser algo que mude o botão curtir mostrando que aquele conteúdo já foi curtido.