config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root :to => redirect('/entrar')
    
  devise_for :professionals, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'profissional/senha', confirmation: 'profissional/confirmar', unlock: 'profissional/desbloquear', sign_up: 'profissional/cadastrar' }, controllers: { sessions: 'sessions', registrations: 'devise/professional_registrations', confirmations: 'devise/professional_confirmations' }
  devise_for :customers, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'cliente/senha', confirmation: 'cliente/confirmar', unlock: 'cliente/desbloquear' }, controllers: { sessions: 'sessions' }, skip: ['registrations']

  as :customer do

    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'cliente' do
      root 'customers#minhas_safiras_por_profissionais', as: :customer_root
      get 'fotos/:token', to: 'photos#index', as: :my_photos
      post 'assign_rewards_to_customer', to: 'rewards#assign_rewards_to_customer', as: :assign_rewards_to_customer
    end
  end

  as :professional do
    
    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'profissional' do
      root 'photos#new', as: :professional_root

      resources :sign_up_steps, only: [:index, :show, :update]
      resources :photos, only: [:new, :create, :destroy]
      post 'get_rewards_by_customers_telephone/', to: 'rewards#get_rewards_by_customers_telephone', as: :get_rewards_by_customers_telephone
      post 'notificacao', to: 'notifications#new', as: :new_notification
    end
  end

  get 'retorno-pagamento', to: 'notifications#retorno_pagamento', as: :retorno_pagamento

  mount Sidekiq::Web, at: '/sidekiq'

  get ":slug", to: 'photos#my_site', as: :professionals_site

  # Esta rota TEM que ser a última da listagem, pois
  # seu objetivo é redirecionar o usuário para uma
  # página 404 no caso onde a rota não existe.
  match '*path', via: :all, to: 'static_pages#error_404'
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
  def generate_back_button_for_professional
    if current_professional.present? && @professional.id == current_professional.id
      # flash.now[:success] = "Convide seus clientes a divulgar seu trabalho e as fotos inseridas serão expostas aqui para que interessados conheçam mais sobre seu trabalho e contato"
      # flash.now[:success] = "Sempre que você convidar um cliente a divulgar seu trabalho, as fotos inseridas serão expostas aqui para que interessados conheçam mais sobre seu trabalho tão logo eles vejam a divulgação feita pelo seu cliente"
      # flash.now[:success] = "Sempre que você convidar um cliente a divulgar seu trabalho, as fotos inseridas serão expostas aqui"
      flash.now[:success] = "
        <ol>
          <li>Convide seus clientes a divulgar seu trabalho;</li>
          <li>O SafiraSalões irá expôr aqui as fotos fornecidas por você;</li>
          <li>O boca-a-boca atrairá pessoas para esta página;</li>
          <li>Os interessados entrarão em contato para marcar horário</li>
        </ol>
      "
      flash_messages
    end
  end

  def nome_profissional
    current_professional.nome
  end

  def professional_widget_title
    case controller_name
    when 'professional_registrations'
      widget_title('tty', 'Dados de Contato')
    when 'services'
      case action_name
      when 'new', 'create'
        widget_title('scissors', 'Cadastrar Serviço')
      when 'edit', 'update'
        widget_title('scissors', 'Editar Serviço')
      when 'index'
        widget_title('scissors', 'Meus Serviços')
      when 'show'
        widget_title('scissors', 'Consultar Serviço')
      end
    when 'schedules'
      widget_title('bullhorn', 'Estimular Cliente a Divulgar Trabalho')
    end
  end

  def professional_widget_subtitle
    case controller_name
    when 'professional_registrations'
      widget_title('tty', 'Informe seu contato para que ele seja divulgado (pelos seus clientes) juntamente com fotos do serviço prestado.')
    when 'services'
      case action_name
      when 'new', 'create'
        widget_title('scissors', 'Cadastre o serviço definindo nome, preço(s) e recompensa(s) por divulgação.')
      when 'edit', 'update'
        widget_title('scissors', 'Altere os campos abaixo e pressione "Salvar" para atualizar o serviço.')
      when 'index'
        widget_title('scissors', 'Cadastre seus serviços para que você possa estimular seus clientes a divulgá-los.')
      when 'show'
        widget_title('scissors', "Veja abaixo os detalhes do serviço #{@service.nome.titleize}.")
      end
    when 'schedules'
      widget_title('bullhorn', 'Informe o cliente e o serviço na agenda abaixo para estimulá-lo a divulgar seu trabalho - selecione uma data.')
    end
  end

  def selected(*options)
    concat content_tag(:span, nil, class: 'selected') if options.include? controller_name
  end

  def build_tour_steps
    if @step_taken.nil? || @step_taken
      normal_tour()
    elsif !@step_taken
      bootstrap_tour()
    end
  end

  private

  def widget_title(icon, text)
    concat content_tag :i, nil, class: "fa fa-#{icon}"
    concat " " + text
  end

  def bootstrap_tour
    case controller_name
    when 'professional_registrations'
      professional_registrations_steps
    when 'services'
      case action_name
      when 'new'
        new_service_steps
      when 'show'
        service_steps
      when 'index'
        services_bootstrap_steps
      when 'edit'
        edit_service_steps
      end
    when 'schedules'
      schedule_steps
    end
  end

  def normal_tour
    case controller_name
    when 'professional_registrations'
      professional_registrations_steps
    when 'services'
      case action_name
      when 'new'
        new_service_steps
      when 'show'
        service_steps
      when 'index'
        services_steps
      when 'edit'
        edit_service_steps
      end
    when 'schedules'
      schedule_steps
    end
  end

  def schedule_steps
    {
      name: "schedule_steps",
      steps: [
        {
          orphan: true,
          backdrop: true,
          title: "<i>O boca-a-boca é a melhor divulgação</i><button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          content: "
          <p>O <b>SafiraSalões</b> <b>incentivará</b> seus clientes a <b>divulgar</b> nas redes sociais <b>seu contato profissional</b>\
          juntamente com as <b>fotos</b> do visual <b>criado por você</b>.</p>",
          template: "
          <div class='popover tour'>
            <div class='arrow'></div>
            <h3 class='popover-title' style='background-color: #c4e2bb'></h3>
            <div class='popover-content'></div>
            <div class='popover-navigation' style='background-color: #c4e2bb'>
              <button class='btn btn-success' data-role='next'>Ótimo! Me mostre como »</button>
            </div>
          </div>"
        },
        {
          element: "#calendar table:nth(0)",
          placement: "top",
          title: "Utilize nossa <b>Agenda</b><button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          content: "
          <p><b>Informe seu próximo cliente</b> e iremos incentivá-lo a <b>divulgar seu trabalho</b>.</p>",
          template: "
          <div class='popover tour'>
            <div class='arrow'></div>
            <h3 class='popover-title' style='background-color: #c4e2bb'></h3>
            <div class='popover-content'></div>
            <div class='popover-navigation' style='background-color: #c4e2bb'>
              <button class='btn btn-danger rounded' data-role='prev'>« </button>
              <button class='btn btn-success rounded btn_tour_agendar pull-right'>Informar cliente »</button>
            </div>
          </div>"
        }
      ],
      backdrop: false,
      keyboard: false,
    }.to_json
  end

  def services_steps
    {
      name: "services_steps",
      steps: [
        {
          placement: 'bottom',
          backdrop: false,
          title: "Área de Serviços<button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          element: "div.panel",
          content: "
          <p>Esta é a área onde você terá controle total sobre seus serviços.</p>
          <p>Sempre que quiser acessá-la basta procurar pela opção 'Quero Divulgar...' > 'Meus Serviços'
          no menu lateral (esquerda).</p>
          ",
          template: "
          <div class='popover tour'>
            <div class='arrow'></div>
            <h3 class='popover-title' style='background-color: #c4e2bb'></h3>
            <div class='popover-content'></div>
            <div class='popover-navigation' style='background-color: #c4e2bb'>
              <button class='btn btn-success' data-role='next'>Próximo »</button>
            </div>
          </div>"
        },
        {
          placement: 'top',
          title: "Tenha controle sobre seus serviços<button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          backdrop: false,
          element: "table#table",
          content: "
          <p>Visualize os serviços cadastrados, os preços e as recompensas. Tudo em um só lugar.</p>
          "
        },
        {
          placement: 'left',
          title: "Gerencie serviços com facilidade <button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          backdrop: false,
          element: "tbody>tr td:last",
          content: "
          <p>Consulte, altere ou exclua seus serviços de maneira muito fácil.</p>
          "
        },
        {
          placement: 'bottom',
          title: "Cadastre novos serviços <button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          backdrop: false,
          element: "a.btn.btn-success.btn-lg",
          content: "
          <p>Cadastre novos serviços clicando em 'Cadastrar Serviço'.</p>
          "
        }
      ],
      backdrop: true,
      keyboard: false,
      template: "
          <div class='popover tour'>
            <div class='arrow'></div>
            <h3 class='popover-title' style='background-color: #c4e2bb'></h3>
            <div class='popover-content'></div>
            <div class='popover-navigation' style='background-color: #c4e2bb'>
            <button class='btn btn-danger' data-role='prev'>« Anterior</button>
              <button class='btn btn-success' data-role='next'>Próximo »</button>
            </div>
          </div>"
    }.to_json
  end

  def services_bootstrap_steps
    {
      name: "services_bootstrap",
      steps: [
        {
          placement: 'bottom',
          backdrop: false,
          title: "Área de Serviços<button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          element: "div.panel",
          content: "
          <p>Esta é a área onde você terá controle total sobre seus serviços.</p>
          <p>Sempre que quiser acessá-la basta procurar pela opção 'Meus Serviços'
          no menu lateral (esquerda).</p>
          ",
          template: "
          <div class='popover tour'>
            <div class='arrow'></div>
            <h3 class='popover-title' style='background-color: #c4e2bb'></h3>
            <div class='popover-content'></div>
            <div class='popover-navigation' style='background-color: #c4e2bb'>
              <button class='btn btn-success' data-role='next'>Próximo »</button>
            </div>
          </div>"
        },
        {
          placement: 'bottom',
          title: "Criar recompensa para divulgação<button type='button' class='close' data-role='end'><span aria-hidden='true'>&times;</span></button>",
          backdrop: false,
          element: "tbody a.btn-warning:first",
          content: "

app/views/layouts/professional/_footer.html.erb
<!-- Start footer content -->
<footer class="footer-content">
    2014 - <span id="copyright-year"></span> &copy; <%= link_to 'SafiraSaloes', professional_root_path %>
    <span class="pull-right">0.01 GB(0%) of 15 GB used</span>
</footer><!-- /.footer-content -->
<!--/ End footer content -->

app/views/layouts/professional/_main_content.html.erb
<!-- START @PAGE CONTENT -->
<section id="page-content">

    <!-- Start page header -->
    <div class="header-content">
        <h2><% professional_widget_title %> <!-- <span>Just-add-water CSS animations</span> --></h2>
        <!-- /.breadcrumb-wrapper
        <div class="breadcrumb-wrapper hidden-xs">
            <span class="label">You are here:</span>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="dashboard.html">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li class="active">Animate.css</li>
            </ol>
        </div> -->
    </div><!-- /.header-content -->
    <!--/ End page header -->

    <!-- Start body content -->
    <div class="body-content">

        <div class="row">
            <div class="col-md-12">

                <!-- Start animate.css -->
                <div class="panel rounded shadow">
                    <div class="panel-heading test">
                        <div class="pull-left">
                            <h3 class="panel-title"><% professional_widget_subtitle %></h3>
                        </div>
                        <!--
                        <div class="pull-right">
                            <button title="" data-original-title="" class="btn btn-sm" data-action="collapse" data-container="body" data-toggle="tooltip" data-placement="top" data-title="Collapse"><i class="fa fa-angle-up"></i></button>
                            <button title="" data-original-title="" class="btn btn-sm" data-action="remove" data-container="body" data-toggle="tooltip" data-placement="top" data-title="Remove"><i class="fa fa-times"></i></button>
                        </div>-->
                        <div class="clearfix"></div>
                    </div><!-- /.panel-heading -->
                    <div class="panel-body">

                      <%= flash_messages %>
                      <%= yield %>

                    </div><!-- /.panel-body -->
                </div><!-- /.panel -->
                <!--/ End animate.css -->

            </div>
        </div>

    </div><!-- /.body-content -->
    <!--/ End body content -->

    <%# render "layouts/professional/footer" %>

</section><!-- /#page-content -->
<!--/ END PAGE CONTENT -->

app/views/layouts/professional/_main_header.html.erb
<!--START @HEADER -->
<header id="header">

    <!-- Start header left -->
    <div class="header-left">
        <!-- Start offcanvas left: This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
        <div class="navbar-minimize-mobile left">
            <i class="fa fa-bars"></i>
        </div>
        <!--/ End offcanvas left -->

        <!-- Start navbar header -->
        <div class="navbar-header" style="background-color: #c4e2bb">

            <!-- Start brand -->
            <%= link_to '', class: "navbar-brand" do %>
                <%= image_tag "logo175x50.png", class: 'logo', alt: 'SafiraSalões' %>
            <% end %>
            
            <!--/ End brand -->

        </div><!-- /.navbar-header -->
        <!--/ End navbar header -->

        <!-- Start offcanvas right: This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
        <div class="navbar-minimize-mobile right passos-tutorial" data-auto-start="<%= @step_taken.nil? ? false : !@step_taken %>" data-tour="<%= build_tour_steps %>">
            <i class="fa fa-question"></i>
        </div>
        <!--/ End offcanvas right -->

        <div class="clearfix"></div>
    </div><!-- /.header-left -->
    <!--/ End header left -->

    <!-- Start header right -->
    <div class="header-right">
        
        <!-- Start navbar toolbar -->
        <div class="navbar navbar-toolbar">

            <!-- Start left navigation -->
            <ul class="nav navbar-nav navbar-left">

                <!-- Start sidebar shrink -->
                <li class="navbar-minimize">
                    <a href="javascript:void(0);" title="Minimize sidebar">
                        <i class="fa fa-bars"></i>
                    </a>
                </li>
                <!--/ End sidebar shrink -->

                <!--/ End form search -->

            </ul><!-- /.navbar-left -->
            <!--/ End left navigation -->

            <ul class="nav navbar-nav navbar-right"><!-- /.nav navbar-nav navbar-right -->
                <!-- Start profile -->
                <li class="navbar-setting pull-right passos-tutorial" style="font-size: 24px; border-left: 1px solid #dddddd; padding: 16px 15px 13px; color: white; background-color: #81b71a; cursor: pointer;" data-auto-start="<%= @step_taken.nil? ? false : !@step_taken %>" data-tour="<%= build_tour_steps %>">
                    <span><i class="fa fa-question"></i></span>
                </li>
                <!--/ End profile -->
            </ul>


        </div><!-- /.navbar-toolbar -->
        <!--/ End navbar toolbar -->
    </div><!-- /.header-right -->
    <!--/ End header left -->

</header> <!-- /#header -->
<!--/ END HEADER -->

app/views/layouts/professional/_secondary_header.html.erb
  <header>
    <% alertas_assinatura %>
  </header>

app/views/layouts/professional/_sidebar.html.erb
<!--

START @SIDEBAR LEFT
|=========================================================================================================================|
|  TABLE OF CONTENTS (Apply to sidebar left class)                                                                        |
|=========================================================================================================================|
|  01. sidebar-box               |  Variant style sidebar left with box icon                                              |
|  02. sidebar-rounded           |  Variant style sidebar left with rounded icon                                          |
|  03. sidebar-circle            |  Variant style sidebar left with circle icon                                           |
|=========================================================================================================================|

-->
<aside id="sidebar-left" class="sidebar-circle">

    <!-- Start left navigation - profile shortcut -->
    <div class="sidebar-content">
        <div class="media">
            <a class="pull-left has-notif avatar">
                <% if current_professional.avatar_url.present? %>
                    <%= image_tag current_professional.avatar_url %>
                <% end %>
                <!-- <i class="online"></i> -->
            </a>
            <div class="media-body">
                <h4 class="media-heading"><%= "Olá, <span>#{current_professional.nome}</span>".html_safe if current_professional.nome.present? %></h4>
                <!-- <small>Web Designer</small> -->
            </div>
        </div>
    </div><!-- /.sidebar-content -->
    <!--/ End left navigation -  profile shortcut -->

    <!-- Start left navigation - menu -->
    <ul class="sidebar-menu">

        <!-- Start navigation - dashboard -->
        <li class="<%= active('photos') %>">
          <%= link_to(new_photo_path, id: 'photo', class: active('photos')) do %>
            <span class="icon"><i class="fa fa-bullhorn"></i></span>
            <span class="text">Convidar Cliente a Divulgar</span>
            <% selected('photos') %>
          <% end %>
        </li>

        <li>
          <%= link_to(professionals_site_path(current_professional), id: 'site') do %>
            <span class="icon"><i class="fa fa-heartbeat"></i></span>
            <span class="text">Meu Site</span>
          <% end %>
        </li>
        
        <!--/ End navigation - dashboard -->

    </ul><!-- /.sidebar-menu -->
    <!--/ End left navigation - menu -->

    <!-- Start left navigation - footer -->
    <div class="sidebar-footer">
        <%= link_to destroy_session_path(current_resource), :method => :delete, id: "logout", 'data-url' => "page-lock-screen.html", class: "pull-left", style: "margin: 0% 30%;", 'data-toggle' => "tooltip", 'data-placement' => "top", 'data-title' => "Sair" do %>
          <i class="fa fa-power-off"></i> Sair
        <% end %>
    </div><!-- /.sidebar-footer -->
    <!--/ End left navigation - footer -->

</aside><!-- /#sidebar-left -->
<!--/ END SIDEBAR LEFT -->

app/views/layouts/professional/_woopra.html.erb
<!-- Start of Woopra Code -->
<script>
(function(){
        var t,i,e,n=window,o=document,a=arguments,s="script",r=["config","track","identify","visit","push","call","trackForm","trackClick"],c=function(){var t,i=this;for(i._e=[],t=0;r.length>t;t++)(function(t){i[t]=function(){return i._e.push([t].concat(Array.prototype.slice.call(arguments,0))),i}})(r[t])};for(n._w=n._w||{},t=0;a.length>t;t++)n._w[a[t]]=n[a[t]]=n[a[t]]||new c;i=o.createElement(s),i.async=1,i.src="//static.woopra.com/js/t/5.js",e=o.getElementsByTagName(s)[0],e.parentNode.insertBefore(i,e)
})("woopra");

woopra.config({
    domain: 'safirasaloes.com.br'
});
// Identify customer
woopra.identify({
    email: "<%= current_professional.email %>",
    name: "<%= current_professional.nome %>",
    user_type: 'professional',
    professional_plan: "<%= current_professional.status.nome.capitalize %>",
    telefone: "<%= current_professional.telefone %>",
    whatsapp: "<%= current_professional.whatsapp %>",
    avatar: "<%= current_professional.avatar_url %>"
});
 
// The line above is equivalent to
woopra.track("pv", {
    url: window.location.pathname,
    title: document.title,
    error: $("div.alert.alert-danger.fade.in li").text()
});
</script>
<!-- End of Woopra Code -->

app/views/layouts/professional/professional.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

    <!-- START @HEAD -->
    <head>
        <!-- START @META SECTION -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title><%= ( title =  yield(:title) ).present? ? title : 'SafiraSaloes' %></title>
        <!--/ END META SECTION -->

        <!-- START @FAVICONS -->
        <!--<link href="../../../img/ico/apple-touch-icon-144x144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144">-->
        <!--<link href="../../../img/ico/apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114">-->
        <!--<link href="../../../img/ico/apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72">-->
        <!--<link href="../../../img/ico/apple-touch-icon-57x57-precomposed.png" rel="apple-touch-icon-precomposed">-->
        <!--<link href="../../../img/ico/apple-touch-icon.png" rel="shortcut icon">-->
        <%= favicon_link_tag      'favicon.png', rel: "shortcut icon" %>
        <!--/ END FAVICONS -->
        
        <!-- START @FONT STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet">
        <!--/ END FONT STYLES -->
        
        <%= render "layouts/hotjar.html" if Rails.env.production? %>
        <%= stylesheet_link_tag   'application', media: 'all' %>
        <%= render "layouts/fb_pixel.html" if Rails.env.production? %>
        <%= csrf_meta_tags %>

        <!-- START @IE SUPPORT -->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="../../../assets/global/plugins/bower_components/html5shiv/dist/html5shiv.min.js"></script>
        <script src="../../../assets/global/plugins/bower_components/respond-minmax/dest/respond.min.js"></script>
        <![endif]-->
        <!--/ END IE SUPPORT -->
    </head>
    <!--/ END HEAD -->

    <!--

    |=========================================================================================================================|
    |  TABLE OF CONTENTS (Use search to find needed section)                                                                  |
    |=========================================================================================================================|
    |  01. @HEAD                        |  Container for all the head elements                                                |
    |  02. @META SECTION                |  The meta tag provides metadata about the HTML document                             |
    |  03. @FAVICONS                    |  Short for favorite icon, shortcut icon, website icon, tab icon or bookmark icon    |
    |  04. @FONT STYLES                 |  Font from google fonts                                                             |
    |  05. @GLOBAL MANDATORY STYLES     |  The main 3rd party plugins css file                                                |
    |  06. @PAGE LEVEL STYLES           |  Specific 3rd party plugins css file                                                |
    |  07. @THEME STYLES                |  The main theme css file                                                            |
    |  08. @IE SUPPORT                  |  IE support of HTML5 elements and media queries                                     |
    |=========================================================================================================================|
    |  09. @BODY                        |  Contains all the contents of an HTML document                                      |
    |  10. @WRAPPER                     |  Wrapping page section                                                              |
    |  11. @HEADER                      |  Header page section contains about logo, top navigation, notification menu         |
    |  12. @SIDEBAR LEFT                |  Sidebar page section contains all sidebar menu left                                |
    |  13. @PAGE CONTENT                |  Contents page section contains breadcrumb, content page, footer page               |
    |  14. @SIDEBAR RIGHT               |  Sidebar page section contains all sidebar menu right                               |
    |  15. @BACK TOP                    |  Element back to top and action                                                     |
    |=========================================================================================================================|
    |  16. @CORE PLUGINS                |  The main 3rd party plugins script file                                             |
    |  17. @PAGE LEVEL PLUGINS          |  Specific 3rd party plugins script file                                             |
    |  18. @PAGE LEVEL SCRIPTS          |  The main theme script file                                                         |
    |=========================================================================================================================|

    START @BODY
    |=========================================================================================================================|
  |  TABLE OF CONTENTS (Apply to body class)                                                                                |
  |=========================================================================================================================|
    |  01. page-boxed                   |  Page into the box is not full width screen                                         |
  |  02. page-header-fixed            |  Header element become fixed position                                               |
  |  03. page-sidebar-fixed           |  Sidebar element become fixed position with scroll support                          |
  |  04. page-sidebar-minimize        |  Sidebar element become minimize style width sidebar                                |
  |  05. page-footer-fixed            |  Footer element become fixed position with scroll support on page content           |
  |  06. page-sound                   |  For playing sounds on user actions and page events                                 |
  |=========================================================================================================================|

  -->
    <body>

        <!--[if lt IE 9]>
        <p class="upgrade-browser">Oppsss!! Você está usando um navegador <strong>desatualizado</strong>. Por favor <a href="http://browsehappy.com/" target="_blank">atualize seu navegador</a> para melhor utilizar nosso sistema.</p>
        <![endif]-->

        <!-- START @WRAPPER -->
        <section id="wrapper">
          <%= render "layouts/professional/main_header" %>
          <%# render "layouts/professional/secondary_header" %>
          <div class="content">
            <%= render "layouts/professional/sidebar" unless current_professional.suspenso? %>
            <%= yield :modals unless current_professional.suspenso? || current_professional.bloqueado? %>
            <%= render "layouts/professional/main_content" unless current_professional.suspenso? %>
          </div>
          <%= javascript_include_tag 'application' %>
          <%= render "layouts/professional/woopra.html" if Rails.env.production? %>
          <%# render "layouts/professional/webengage_professional" if Rails.env.production? %>
          <%# subscribe_to "/professional/email_invitation_problem/#{current_professional.id}" %>

        </section><!-- /#wrapper -->
        <!--/ END WRAPPER -->

        <!-- START @BACK TOP -->
        <div id="back-top" class="animated pulse circle">
            <i class="fa fa-angle-up"></i>
        </div><!-- /#back-top -->
        <!--/ END BACK TOP -->

    </body>
    <!--/ END BODY -->

</html>