config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root :to => redirect('/entrar')
    
  devise_for :professionals, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'profissional/senha', confirmation: 'profissional/confirmar', unlock: 'profissional/desbloquear', sign_up: 'profissional/cadastrar' }, controllers: { sessions: 'sessions', registrations: 'devise/professional_registrations', confirmations: 'devise/professional_confirmations' }
  devise_for :customers, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'cliente/senha', confirmation: 'cliente/confirmar', unlock: 'cliente/desbloquear' }, controllers: { sessions: 'sessions' }, skip: ['registrations']

  as :customer do

    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'cliente' do
      root 'customers#minhas_safiras_por_profissionais', as: :customer_root
      get 'fotos/:token', to: 'photos#index', as: :my_photos
      post 'assign_rewards_to_customer', to: 'rewards#assign_rewards_to_customer', as: :assign_rewards_to_customer
    end
  end

  as :professional do
    
    get "/auth/:provider/callback", :to => "omniauth_callbacks#facebook"
    get '/auth/failure', to: redirect('/')
    
    scope 'profissional' do
      root 'photos#new', as: :professional_root

      resources :sign_up_steps, only: [:index, :show, :update]
      resources :photos, only: [:new, :create, :destroy]
      post 'get_rewards_by_customers_telephone/', to: 'rewards#get_rewards_by_customers_telephone', as: :get_rewards_by_customers_telephone
      post 'notificacao', to: 'notifications#new', as: :new_notification
    end
  end

  get 'retorno-pagamento', to: 'notifications#retorno_pagamento', as: :retorno_pagamento

  mount Sidekiq::Web, at: '/sidekiq'

  get ":slug", to: 'photos#my_site', as: :professionals_site

  # Esta rota TEM que ser a última da listagem, pois
  # seu objetivo é redirecionar o usuário para uma
  # página 404 no caso onde a rota não existe.
  match '*path', via: :all, to: 'static_pages#error_404'
end

app/controllers/sign_up_steps_controller.rb
class SignUpStepsController < ApplicationController
  include Wicked::Wizard
  steps :contact_info

  def show; render_wizard; end
end

app/helpers/sign_up_steps_helper.rb
module SignUpStepsHelper
  def resource_name
    :professional
  end

  def resource
    @resource ||= current_professional
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:professional]
  end
end

app/views/sign_up_steps/contact_info.html.erb
<%= content_for :title, 'Cadastrar | SafiraSalões' %>

<!-- Login form -->
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, class: "sign-in form-horizontal shadow rounded no-overflow" }) do |f| %>
    <div class="sign-header">
      <div class="form-group">
        <div class="sign-text">
          <% if current_professional.avatar_url.present? %>
            <%= image_tag current_professional.avatar_url, class: "img-circle" %>
            <p style="text-transform: none;"><strong><%= current_professional.nome %></strong>, informe os telefones onde seus futuros clientes marcarão horários</p>
          <% else %>
          <p style="text-transform: none;">Informe os telefones onde seus futuros clientes marcarão horários</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="sign-body" style="padding: 15px 0px;">
      <div class="form-group">
        <div class="input-group input-group-lg rounded no-overflow">
          <%= f.text_field :nome, class: "form-control input-sm", placeholder: "Nome", autofocus: true %>
          <span class="input-group-addon"><i class="fa fa-user"></i></span>
        </div>
      </div><!-- /.form-group -->
      <div class="form-group">
        <div class="input-group input-group-lg rounded no-overflow">
          <%= f.text_field :telefone, class: "form-control input-sm telefone", placeholder: 'Telefone para marcar horário' %>
          <span class="input-group-addon"><i class="fa fa-mobile"></i></span>
        </div>
      </div><!-- /.form-group -->
      <div class="form-group">
        <div class="input-group input-group-lg rounded no-overflow">
          <%= f.text_field :whatsapp, class: "form-control input-sm telefone", placeholder: 'WhatsApp para marcar horário' %>
          <span class="input-group-addon"><i class="fa fa-whatsapp"></i></span>
        </div>
      </div><!-- /.form-group -->
    </div><!-- /.sign-body -->
    <div class="sign-footer">
      <div class="form-group">
        <%= button_tag 'Quero Clientes AGORA!', class: "btn btn-theme btn-lg btn-block no-margin rounded", id: "login-btn", type: 'submit' %>
      </div><!-- /.form-group -->
    </div><!-- /.sign-footer -->
<% end %><!-- /.form-horizontal -->